##data zipfile located in working directory
data <- unzip("./exdata-data-household_power_consumption.zip")
power <- read.table(data,sep=";",header=TRUE,na.strings="?",colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
power$DateTime <- paste(power$Date,power$Time)
Feb1_power <- subset(power, power$Date == "1/2/2007")
Feb2_power <- subset(power,power$Date =="2/2/2007")
Feb1_Feb2 <- rbind(Feb1_power,Feb2_power)
Feb1_Feb2$DateTime <- strptime(Feb1_Feb2$DateTime,"%d/%m/%Y %H:%M:%S")
png(filename="plot3.png",width=480,height=480)
plot(Feb1_Feb2$DateTime,Feb1_Feb2$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
points(Feb1_Feb2$DateTime,Feb1_Feb2$Sub_metering_1,type="l")
points(Feb1_Feb2$DateTime,Feb1_Feb2$Sub_metering_2,type="l",col="red")
points(Feb1_Feb2$DateTime,Feb1_Feb2$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty="solid")
dev.off()
